version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 99

  - package-ecosystem: npm
    directory: '/react'
    schedule:
      interval: weekly
      day: saturday
    open-pull-requests-limit: 99

  - package-ecosystem: npm
    directory: '/vue'
    schedule:
      interval: weekly
      day: saturday
    open-pull-requests-limit: 99

  - package-ecosystem: npm
    directory: '/svelte'
    schedule:
      interval: weekly
      day: saturday
    open-pull-requests-limit: 99

  - package-ecosystem: npm
    directory: '/web'
    schedule:
      interval: weekly
      day: saturday
    open-pull-requests-limit: 99
